// Generated by CoffeeScript 1.6.1
(function() {
  var db, redis, restify, server;

  restify = require('restify');

  server = restify.createServer();

  server.use(restify.bodyParser());

  redis = require('redis');

  db = redis.createClient(6379, 'incandenza.ucc.asn.au');

  server.get('/hi', function(request, response, next) {
    response.send('hey');
    return next();
  });

  server.get('/game/load/:hash', function(request, response, next) {
    return db.get(request.params.hash, function(err, reply) {
      if (reply != null) {
        response.send(reply);
      } else {
        response.send(404);
      }
      return next();
    });
  });

  server.post('/game/save', function(request, response, next) {
    console.log(request.body);
    response.send(request.body.foo);
    return next();
  });

  server.listen(7937, 'localhost', function() {
    return console.log('%s listening at %s', server.name, server.url);
  });

}).call(this);
