// Generated by CoffeeScript 1.6.1
(function() {
  var cryptical, crypto, db, redis, restify, server;

  cryptical = {};

  restify = require('restify');

  server = restify.createServer();

  server.use(restify.bodyParser());

  server.use(restify.fullResponse());

  redis = require('redis');

  db = redis.createClient(6379, 'incandenza.ucc.asn.au');

  crypto = require('crypto');

  cryptical.hash = function(str) {
    return crypto.createHash('sha1').update(str).digest('hex');
  };

  server.get('/hi', function(request, response, next) {
    response.send('hey');
    return next();
  });

  server.get('/game/load/:hash', function(request, response, next) {
    return db.get(request.params.hash, function(err, reply) {
      if (reply != null) {
        response.send(reply);
      } else {
        response.send(404);
      }
      return next();
    });
  });

  server.get('/game/save', function(req, res, next) {
    return res.send('fuck you');
  });

  server.post('/game/save', function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "http://localhost:7793");
    res.header("Access-Control-Allow-Headers", "X-Requested-With");
    res.send('thanks for ' + cryptical.hash(req.body) + '!');
    return next();
  });

  server.listen(7937, 'localhost', function() {
    return console.log('%s listening at %s', server.name, server.url);
  });

}).call(this);
